src/AppBundle/Entity/Product.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\File;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * Product
 *
 * @ORM\Table(name="product")
 * @ORM\Entity(repositoryClass="AppBundle\Repository\ProductRepository")
 * @Vich\Uploadable
 */
class Product
{
    const STATUS_NEW = 0;
    const STATUS_ON_SALE = 1;
    const STATUS_SOLD = 2;
    const STATUS_BLOCKED = 2;

    const DEFAULT_PAGE_SIZE = 12;

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var int
     *
     * @ORM\Column(name="status", type="integer")
     */
    private $status;

    /**
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255)
     */
    private $title;

    /**
     * @ORM\ManyToOne(targetEntity="User", inversedBy="products")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $owner;

    /**
     * @var string
     *
     * @ORM\Column(name="description", type="text")
     */
    private $description;

    /**
     * @var Category
     *
     * @ORM\ManyToOne(targetEntity="Category", inversedBy="products")
     * @ORM\JoinColumn(name="category_id", referencedColumnName="id")
     */
    private $category;

    /**
     * @var string
     *
     * @ORM\Column(name="tags", type="simple_array", length=255)
     */
    private $tags;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="create_at", type="datetime")
     */
    private $createAt;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="updated_at", type="datetime")
     */
    private $updatedAt;

    /**
     * @var string
     *
     * @ORM\Column(name="price", type="decimal", precision=10, scale=2)
     */
    private $price;

    /**
     * @var int
     *
     * @ORM\Column(name="likes", type="integer")
     */
    private $likes;

    /**
     * @var ProductOrder[]
     * @ORM\OneToMany(targetEntity="ProductOrder", mappedBy="product")
     */
    private $orders;

    /**
     * @var License
     *
     * @ORM\ManyToOne(targetEntity="License", inversedBy="products")
     * @ORM\JoinColumn(name="license_id", referencedColumnName="id")
     */
    private $license;

    /**
     * @var string
     *
     * @ORM\Column(name="slug", type="string", length=255)
     */
    private $slug;

    /**
     * @var string
     *
     * @ORM\Column(name="head_picture", type="string", length=255)
     */
    private $headPicture;

    /**
     * @var string
     *
     * @ORM\Column(name="origin_file_name", type="string", length=255)
     */
    private $origin;

    public static $adminStatuses = [
        self::STATUS_NEW => 'new',
        self::STATUS_ON_SALE => 'active',
        self::STATUS_BLOCKED => 'blocked',
    ];


    public function __construct()
    {
        $this->price = 0;
        $this->likes = 0;
        $this->status = self::STATUS_NEW;
    }

    /**
     * @return string
     */
    public function getOrigin()
    {
        return $this->origin;
    }

    /**
     * @param string $origin
     */
    public function setOrigin($origin)
    {
        $this->origin = $origin;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return Product
     */
    public function setTitle($title)
    {
        $this->title = $title;

        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Product
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * @return Category
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * @param Category $category
     */
    public function setCategory($category)
    {
        $this->category = $category;
    }

    /**
     * Set tags
     *
     * @param string $tags
     * @return Product
     */
    public function setTags($tags)
    {
        $this->tags = $tags;

        return $this;
    }

    /**
     * Get tags
     *
     * @return string 
     */
    public function getTags()
    {
        return $this->tags;
    }

    /**
     * Set createAt
     *
     * @param \DateTime $createAt
     * @return Product
     */
    public function setCreateAt($createAt)
    {
        $this->createAt = $createAt;

        return $this;
    }

    /**
     * Get createAt
     *
     * @return \DateTime 
     */
    public function getCreateAt()
    {
        return $this->createAt;
    }

    /**
     * Set updatedAt
     *
     * @param \DateTime $updatedAt
     * @return Product
     */
    public function setUpdatedAt($updatedAt)
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    /**
     * Get updatedAt
     *
     * @return \DateTime 
     */
    public function getUpdatedAt()
    {
        return $this->updatedAt;
    }

    /**
     * Set price
     *
     * @param string $price
     * @return Product
     */
    public function setPrice($price)
    {
        $this->price = $price;

        return $this;
    }

    /**
     * Get price
     *
     * @return string 
     */
    public function getPrice()
    {
        return $this->price;
    }

    public function getFormattedPrice()
    {
        return '$' . $this->getPrice();
    }

    /**
     * Set likes
     *
     * @param integer $likes
     * @return Product
     */
    public function setLikes($likes)
    {
        $this->likes = $likes;

        return $this;
    }

    /**
     * Get likes
     *
     * @return integer 
     */
    public function getLikes()
    {
        return $this->likes;
    }

    /**
     * @return License
     */
    public function getLicense()
    {
        return $this->license;
    }

    /**
     * @param License $license
     */
    public function setLicense($license)
    {
        $this->license = $license;
    }

    /**
     * Set slug
     *
     * @param string $slug
     * @return Product
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * Get slug
     *
     * @return string 
     */
    public function getSlug()
    {
        return $this->slug;
    }

    /**
     * Set headPicture
     *
     * @param string $headPicture
     * @return Product
     */
    public function setHeadPicture($headPicture)
    {
        $this->headPicture = $headPicture;

        return $this;
    }

    /**
     * Get headPicture
     *
     * @return string 
     */
    public function getHeadPicture()
    {
        return $this->headPicture;
    }

    /**
     * @return User
     */
    public function getOwner()
    {
        return $this->owner;
    }

    /**
     * @param User $owner
     */
    public function setOwner($owner)
    {
        $this->owner = $owner;
    }

    /**
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * @param int $status
     */
    public function setStatus($status)
    {
        $this->status = $status;
    }

    /**
     * @return ProductOrder[]
     */
    public function getOrders()
    {
        return $this->orders;
    }

    /**
     * @param ProductOrder[] $orders
     */
    public function setOrders($orders)
    {
        $this->orders = $orders;
    }
}

src/AppBundle/Form/ProductForm.php
<?php

namespace AppBundle\Form;

use AppBundle\Repository\CategoryRepository;
use AppBundle\Repository\LicenseRepository;
use AppBundle\Repository\TagRepository;
use AppBundle\Subscriber\ProductFormEventSubscriber;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductForm extends AbstractType
{
    /**
     * @var CategoryRepository
     */
    private $categoryRepository;
    /**
     * @var LicenseRepository
     */
    private $licenseRepository;
    /**
     * @var TagRepository
     */
    private $tagRepository;

    public function __construct(
        CategoryRepository $categoryRepository,
        LicenseRepository $licenseRepository,
        TagRepository $tagRepository
    ) {
        $this->categoryRepository = $categoryRepository;
        $this->licenseRepository = $licenseRepository;
        $this->tagRepository = $tagRepository;
    }

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('title', 'text');
        $builder->add('description', 'textarea');
        $builder->add('categoryId', 'choice', [
            'choices' => $this->categoryRepository->getCategoriesForSelect()
        ]);
        $builder->add('licenseId', 'choice', [
            'choices' => $this->licenseRepository->getLicenseListForSelect()
        ]);
        $builder->add('tags', 'choice', [
            'choices' => $this->tagRepository->getTagListForSelect(),
            'multiple' => true
        ]);
        $builder->add('price', 'money', ['currency' => 'USD']);
        $builder->add('imageFile', 'file');
        $builder->add('originFile', 'file');

        $builder->addEventSubscriber(new ProductFormEventSubscriber());
    }

    public function configureOptions(OptionsResolver $resolver)
    {
    }

    public function getBlockPrefix()
    {
        return 'app_bundle_product_form';
    }
}

src/AppBundle/Controller/ProductsController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Product;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;

class ProductsController extends Controller
{
    /**
     * @Route(path="/products", name="products_list")
     */
    public function indexAction(Request $request)
    {
        $repository = $this->get('app.repository.product');
        $page = $request->get('page',0);

        return $this->render('@App/products/list_products.html.twig', [
            'pageTitle' => 'Miscellaneous products overview',
            'products' => $repository->getProductsForPage($page),
            'pages' => $repository->getPagesAmount(),
            'page' => $page,
        ]);
    }

    /**
     * @Route(path="/products/{id}/view", name="product_view")
     * @param $id
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws NotFoundHttpException
     */
    public function viewAction($id)
    {
        $user = $this->getUser();
        /** @var Product $product */
        $product = $this->get('app.repository.product')->find($id);
        if (!$product || ($product->getStatus() !== Product::STATUS_ON_SALE &&
            $user !== $product->getOwner())
        ) {
            throw new NotFoundHttpException('Page not found');
        }

        return $this->render('@App/products/view.html.twig', [
            'product' => $product,
            'is_owned' => $user === $product->getOwner()
        ]);
    }

    /**
     * @Route(path="/products/search", name="product_search")
     * @param Request $request
     * @return \Symfony\Component\HttpFoundation\Response
     * @throws NotFoundHttpException
     */
    public function searchAction(Request $request)
    {
        $page = $request->get('page', 0);
        $search = $request->get('search', '');
        $products = $this->get('app.repository.product')->searchProducts($search);
        $pages = 0;
        $products = $this->get('app.service.product')->paginate($products, $page, $pages);

        return $this->render('@App/products/list_products.html.twig', [
            'pageTitle' => 'Search results',
            'searched' => $search,
            'products' => $products,
            'page' => $page,
            'pages' => $pages,
            'additional_attributes' => ['search' => $search]
        ]);
    }

    /**
     * @Route(path="/products/filter", name="products_filter")
     */
    public function filterAction()
    {
        $products = $this->get('app.repository.product')->filterProducts(['human', 'kid']);

        return $this->render('@App/products/list_products.html.twig', [
            'pageTitle' => 'Search results',
            'products' => $products
        ]);
    }
}

src/AppBundle/Resources/views/products/index.html.twig
{% extends '@App/layout.html.twig' %}
{% import '@App/products/list_products.html.twig' as macros %}
{% block content %}
    <div class="page-header">
        <h2>{{ 'Overview of uploaded works'|trans }}</h2>
    </div>

    <div class="row img-thumbnails">
        {% for product in products %}
            {{ macros.renderProduct(product) }}
        {% endfor %}
    </div>
{% endblock %}

src/AppBundle/Resources/views/products/list_products.html.twig
{% extends '@App/layout.html.twig' %}
{% import _self as macros %}
{% block content %}
    <div class="page-header">
        <h2>{{ pageTitle|trans }}</h2>
    </div>
    <form class="text-center" method="POST" action="{{ url('product_search') }}">
        <div class="form-group search-bar-wrapper">
            <div class="control-group search-bar-wrapper">
                <input name="search" class="search-bar form-control" placeholder="{{ 'Type in search string'|trans }}" {% if searched is defined %}value="{{ searched }}" {% endif %}/>
            </div>
            <br />
            <div class="control-group">
                <button class="btn btn-primary">{{ 'Search'|trans }}</button>
            </div>
        </div>
    </form>
    <div class="items">
        <div class="row img-thumbnails">
            {% for product in products %}
                {% if not loop.first and loop.index0 is divisible by(3) %}
                    {{ '</div><div class="row img-thumbnails">' }}
                {% endif %}
                {{ macros.renderProduct(product, 'col-md-4') }}
            {% endfor %}
        </div>
    </div>
    {% if page is defined %}
        {% if additional_attributes is not defined %}
            {% set additional_attributes = {} %}
        {% endif %}
        <div class="text-center">
            {{ include('@App/widgets/paginator_widget.html.twig', {'current_page' : page, 'pages' : pages, 'attributes' : additional_attributes }) }}
        </div>
    {% endif %}
{% endblock %}
{% macro renderProduct(product, class) %}
    <div class="{{ class }}">
        <a href="{{ url('product_view', {'id' : product.id}) }}">
            <img src="/uploads/thumbs/{{ product.headPicture }}" class="img-thumbnail">
        </a>
    </div>
{% endmacro %}

src/AppBundle/Resources/views/products/search.html.twig
{% extends '@App/layout.html.twig' %}
{% block content %}

{% endblock %}

src/AppBundle/Resources/views/products/view.html.twig
{% extends '@App/layout.html.twig' %}
{% import _self as macros %}
{% block content %}
    {% if is_owned %}
        <h2 class="text-center">{{ 'My product'|trans }} "{{ product.title }}"</h2>
    {% else %}
        <h2 class="text-center">{{ product.title }}</h2>
    {% endif %}
    {{ include('@App/widgets/author_widget.html.twig', {'author' : product.owner }) }}
    <h4>{{ 'Tags'|trans }}</h4>
    <ul class="tags">
        {% for tag in product.tags %}
            <li>
                <a href="{{ url('product_search', {'page': 0,'search' : tag }) }}" class="tag">{{ tag }}</a>
            </li>
        {% endfor %}
    </ul>
    <p>{{ product.description }}</p>
    <label class="price-wrapper control-label">{{ 'Price:'|trans }}</label><span
        class="price">{{ product.formattedPrice }}</span>
    <div class="image-view-wrapper">
        <img class="image-view" src="/uploads/{{ product.headPicture }}">
    </div>
    <br>
    <div class="control-group">
        {% if app.user %}
            {% if not is_owned %}
                {% if app.user.isProductBought(product.id) %}
                    <a href="{{ url('product_download', {'id' : product.id }) }}"
                       class="btn btn-success">{{ 'Download origin'|trans }}</a>
                {% else %}
                    <a href="{{ url('payment_create', {'id' : product.id }) }}"
                       class="btn btn-success">{{ 'Order NOW!'|trans }}</a>
                {% endif %}
            {% endif %}

        {% else %}
            <a href="{{ url('fos_user_security_login') }}"
               class="btn btn-primary">{{ 'Log in and order!'|trans }}</a>
        {% endif %}
    </div>
{% endblock %}